(function () {
  'use strict';
  // This state belongs to the isolated content-script world, never to page JS.
  if (globalThis.__geminiStudyHelperInstalled) return;
  globalThis.__geminiStudyHelperInstalled = true;
  const ext = globalThis.browser || globalThis.chrome;
  const core = globalThis.ExplainCore;
  let inFlight = false;
  let gesture = null;
  let sequence = 0;
  let activeSelection = null;
  let host = null;

  function isField() {
    let focused = document.activeElement;
    while (focused?.shadowRoot?.activeElement) focused = focused.shadowRoot.activeElement;
    return focused && (/^(INPUT|TEXTAREA|SELECT)$/.test(focused.tagName || '') || focused.isContentEditable);
  }
  function readSelection() {
    const s = window.getSelection();
    return {text: s?.toString() || '', anchor: s?.anchorNode, anchorOffset: s?.anchorOffset, focus: s?.focusNode, focusOffset: s?.focusOffset};
  }
  function selection() {
    if (isField()) return {text: ''};
    const s = window.getSelection();
    const node = s?.anchorNode?.parentElement;
    if (node?.closest('input, textarea, select, [contenteditable]:not([contenteditable="false"])')) return {text: ''};
    return readSelection();
  }
  function same(a, b) {
    return a.text === b.text && a.anchor === b.anchor && a.anchorOffset === b.anchorOffset && a.focus === b.focus && a.focusOffset === b.focusOffset;
  }
  function close() { if (host) host.remove(); host = null; }
  function dismiss() { sequence++; activeSelection = null; close(); }
  function show(answer) {
    close();
    if (!/^[1-4]$/.test(answer)) return;
    host = document.createElement('div');
    host.id = 'gemini-study-helper-overlay';
    for (const [name, value] of Object.entries({
      all: 'initial', display: 'block', position: 'fixed', inset: 'auto',
      left: '16px', bottom: '16px', margin: '0', padding: '0', width: 'auto', height: 'auto',
      background: 'transparent', border: 'none', 'box-shadow': 'none',
      'z-index': '2147483647', 'pointer-events': 'none', transform: 'none', opacity: '1'
    })) host.style.setProperty(name, value, 'important');
    const shadow = host.attachShadow({mode: 'closed'});
    const span = document.createElement('span');
    span.style.cssText = 'all:initial;display:block;color:#000;background:transparent;border:0;box-shadow:none;text-shadow:none;font:24px/1.2 system-ui,sans-serif;user-select:none;';
    span.textContent = answer;
    span.setAttribute('role', 'status');
    shadow.append(span);
    document.documentElement.append(host);
  }
  async function lookup(selected) {
    if (inFlight) return;
    const current = ++sequence;
    close();
    inFlight = true;
    activeSelection = selected;
    try {
      const response = await ext.runtime.sendMessage({type: 'LOOKUP_SELECTION', text: selected.text, requestId: crypto.randomUUID()});
      // Check the range again in case its change event has not been delivered yet.
      if (current === sequence && same(selected, readSelection()) && response?.ok && /^[1-4]$/.test(response.answer)) show(response.answer);
    } catch (_) {
      // The action badge/options own diagnostics. Never render errors on the page.
      try { await ext.runtime.sendMessage({type: 'CONTENT_ERROR'}); } catch (_) { /* Extension reloaded: page reload required. */ }
    } finally {
      // Drop gestures begun while waiting, including an unfinished drag/held Shift.
      gesture = null;
      inFlight = false;
    }
  }
  function finish(g) {
    if (gesture !== g) return;
    gesture = null;
    if (inFlight) return;
    const end = selection();
    // A click on an unchanged selection is not a new selection gesture.
    if (!g.changed && !g.moved && same(g.start, end)) return;
    if (!end.text.trim()) return;
    const normalized = core.normalizeSelection(end.text);
    if (!normalized.ok) {
      ext.runtime.sendMessage({type: 'CONTENT_ERROR', code: normalized.code}).catch(() => {});
      return;
    }
    lookup(end);
  }
  function begin(kind, id, point) {
    if (gesture?.ended) finish(gesture);
    // finish() can start a request. Do not queue another gesture while waiting.
    if (inFlight) return;
    gesture = {kind, id, point, start: selection(), changed: false, moved: false, ended: false};
  }
  function end(kind, id) {
    if (!gesture || gesture.kind !== kind || gesture.id !== id || gesture.ended) return;
    const g = gesture;
    g.ended = true;
    // Selection changes generated by pointerup/keyup settle before committing once.
    setTimeout(() => finish(g), 0);
  }
  document.addEventListener('selectionchange', () => {
    if (activeSelection && !same(activeSelection, readSelection())) dismiss();
    if (gesture && !same(gesture.start, selection())) gesture.changed = true;
  });
  document.addEventListener('pointerdown', e => {
    if (!e.isTrusted || e.button !== 0 || e.isPrimary === false) return;
    begin('pointer', e.pointerId, {x: e.clientX, y: e.clientY});
  }, true);
  document.addEventListener('pointermove', e => {
    const g = gesture;
    if (!e.isTrusted || !(e.buttons & 1) || g?.kind !== 'pointer' || g.id !== e.pointerId || g.ended) return;
    // Reselecting the same range may batch selectionchange until after pointerup.
    // A real drag still counts, whereas an unchanged click or tiny jitter does not.
    if (Math.hypot(e.clientX - g.point.x, e.clientY - g.point.y) > 3) g.moved = true;
  }, true);
  document.addEventListener('pointerup', e => {
    if (e.isTrusted && e.button === 0) end('pointer', e.pointerId);
  }, true);
  document.addEventListener('pointercancel', () => { gesture = null; }, true);
  document.addEventListener('keydown', e => {
    if (!e.isTrusted) return;
    if (e.key === 'Escape') { dismiss(); gesture = null; return; }
    const selectAll = (e.ctrlKey || e.metaKey) && e.key.toLowerCase() === 'a';
    const extend = e.shiftKey && /^(ArrowLeft|ArrowRight|ArrowUp|ArrowDown|Home|End|PageUp|PageDown)$/.test(e.key);
    if ((selectAll || extend) && !gesture && !e.repeat) begin('keyboard', selectAll ? 'a' : 'Shift');
  }, true);
  document.addEventListener('keyup', e => {
    if (e.isTrusted) end('keyboard', e.key.toLowerCase() === 'a' ? 'a' : e.key);
  }, true);
  window.addEventListener('blur', () => { gesture = null; });
})();
